### ISSUE TITLE
BASE_PATH not used

### ISSUE THREAD

**Issue by pasdam** [ory/kratos-selfservice-ui-node#183]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'm using `kratos-selfservice-ui-node:v0.10.1` and I'm trying to make it accessible in a subpath, i.e. `<my-domain>/website`, so I'm setting `BASE_PATH` to be `/website`, but the website is not accessible as it redirects to `<my_domain>/welcome`. From the codebase seems like the env variable is unused, or am I missing something. How can I make the website accessible from a subpath?

### Reproducing the bug

I'm running the services using docker-compose and Traefik as ingress

```yaml
version: '2'
services:

  ingress:
    image: traefik:2.7.1
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--log=true'
      - '--log.level=DEBUG'
    ports:
      - 80:80
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # this is required so Traefik can listen to the Docker events
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`localhost`)'
      - 'traefik.http.routers.api.service=api@internal'
  
  kratos-migrate:
    image: oryd/kratos:v0.10.1
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - ./sqlite:/var/lib/sqlite
      - ./kratos:/etc/config/kratos:ro
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.10.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - ./sqlite:/var/lib/sqlite
      - ./kratos:/etc/config/kratos:ro

  website:
    image: oryd/kratos-selfservice-ui-node:v0.10.1
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      # - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - PORT=4455
      - SECURITY_MODE=
      - BASE_PATH=/website
      - BASE_URL=/website
    ports:
      - 4455:4455
    restart: on-failure
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.website.rule=Host(`localhost`) && (PathPrefix(`/website`) || Path(`/welcome`))'
      - "traefik.http.routers.website.middlewares=website-strip-prefix@docker"
      - "traefik.http.middlewares.website-strip-prefix.stripprefix.prefixes=/website"
      - "traefik.http.services.website.loadbalancer.server.port=4455"
```

### Version

v0.10.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose
