### ISSUE TITLE
Wrong image for Dockerfile-dev

### ISSUE THREAD

**Issue by miniben-90** [ory/kratos-selfservice-ui-node#205]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

A small error with `Dockerfile-dev` the version of `node` image does not exist.
Should be replace by  `node:18.0-alpine` or `node:18-alpine` to use the latest image of node.

### Reproducing the bug

Using compose to deploy local stack ory kratos and ui :
```yaml
version: '3.7'
services:
  kratos-selfservice-ui-node:
    build:
      context: '[path to the ui project]'
      dockerfile: Dockerfile-dev
    volumes:
      - '[path to the ui project]'
    environment:
      - PORT=4435
      /*...*/
```

### Version

0.10.1

### In which environment are you deploying?

Docker Compose
