### ISSUE TITLE
Submit button address of the signin is incorrect

### ISSUE THREAD

**Issue by wimmerX** [ory/kratos-selfservice-ui-node#206]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The submit button address of the user interface is incorrect，`kratos-76b4cd684c-fh2hj`is kratos pod name in a k8s cluster.How to correct it ? Create users also have similar problems.
![image](https://user-images.githubusercontent.com/57867911/193875567-97dd8820-c852-4042-9768-535438770bd5.png)

kratos.yaml:
```
ciphers:
  algorithm: xchacha20-poly1305
cookies:
  domain: caas.fii-fmc.com
  path: /
  same_site: Lax
courier:
  smtp: {}
hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8
identity:
  default_schema_id: default
  schemas:
  - id: default
    url: file:///etc/config/userSchemaJson
log:
  format: text
  leak_sensitive_values: true
  level: debug
selfservice:
  allowed_return_urls:
  - https://foobar.com
  default_browser_return_url: https://foobar.com/
  flows:
    error:
      ui_url: https://foobar.com/error
    login:
      lifespan: 10m
      ui_url: https://foobar.com/login
    logout:
      after:
        default_browser_return_url: https://foobar.com/login
    recovery:
      enabled: true
      ui_url: https://foobar.com/recovery
    registration:
      after:
        password:
          hooks:
          - hook: session
      lifespan: 10m
      ui_url: https://foobar.com/registration
    settings:
      privileged_session_max_age: 15m
      ui_url: https://foobar.com/settings
    verification:
      after:
        default_browser_return_url: https://foobar.com/
      enabled: true
      ui_url: https://foobar.com/verification
  methods:
    password:
      enabled: true
serve:
  admin:
    port: 4434
  public:
    port: 4433
```

`kratos-selfservice-ui-node` pod env parameters:
```
env:
        - name: KRATOS_PUBLIC_URL
          value: http://kratos-public
        - name: KRATOS_BROWSER_URL
          value: https://public.kratos.foobar.com
        - name: PROJECT_NAME
          value: SecureApp
        - name: BASE_URL
        - name: JWKS_URL
          value: http://oathkeeper-api
        - name: KRATOS_ADMIN_URL
          value: http://kratos-admin
        - name: SECURITY_MODE
```

### Reproducing the bug

1.
```
helm install --debug kratos --dry-run  ory/kratos \
-f kratos.yaml \
--set-file kratos.identitySchemas.userSchemaJson=user.schema.json
```
2.
```
helm install --debug kratos-selfservice-ui-node \       
ory/kratos-selfservice-ui-node
```

### Version

oryd/kratos:v0.10.1&&oryd/kratos-selfservice-ui-node:v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
