### ISSUE TITLE
KRATOS_BROWSER_URL not effective on webauthn script src

### ISSUE THREAD

**Issue by dbtek** [ory/kratos-selfservice-ui-node#226]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Script src seems to use 127.0.0.1 origin to fallback.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/310612/205449643-94f2bd4d-55ca-4422-8fc6-eeef1730a995.png">

### Reproducing the bug

1. Run Kratos with webauthn enabled.
2. Run self-service with given docker-compose config (Kratos config stripped)
3. Login and navigate to account settings.

### Relevant configuration

```yml
# docker-compose.yml
version: '3.7'
services:
  selfservice:
    image: oryd/kratos-selfservice-ui-node
    environment:
    - KRATOS_PUBLIC_URL=http://kratos:4433/
    - KRATOS_BROWSER_URL=http://127.0.0.1:8001/authn/
    - BASE_PATH=/auth
    - PORT=4455
    - SECURITY_MODE=
    networks:
    - intranet
    restart: on-failure
    ports:
     - "4455:4455"
```

### Version

0.11.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

### Additional Context

I would happily drop a PR if guided, since I couldn't be sure where this issue fixed.
I'm sorry if I missed or did something wrong.

Thanks!
