### ISSUE TITLE
ui doesn't understand that i'm signed in

### ISSUE THREAD

**Issue by aurokk** [ory/kratos-selfservice-ui-node#232]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hello! 
I'm experimenting with Kratos and the UI project.
When I'm signing in with google I need to press the sign-in button again or navigate to / for UI to refresh its state. 
What am I doing wrong?

https://user-images.githubusercontent.com/7325744/207965619-eea5d66b-75dc-42e6-9448-e3c9d5a37f38.mp4

Also, I attached my configuration.

### Reproducing the bug

Sign in with google. 
You can use my deployment https://ui.kratos.aurokk.com/.
The problem appears only when you face a google consent screen (you'll face it every time if you have multiple google accounts signed in, or you sign in for the first time). If there is no consent screen — it works as expected!

### Relevant configuration

```yml
kratos:
  config:
    dsn: ...
    secrets:
      default:
        - ...
        - ...
    identity:
      default_schema_id: user_v0
      schemas:
        - id: user_v0
          url: file:///etc/config/user_v0.schema.json
    courier:
      smtp:
        connection_uri: ...
        from_address: noreply@aurokk.com
        from_name: Words
    serve:
      public:
        base_url: https://kratos.aurokk.com/
    selfservice:
      default_browser_return_url: https://ui.kratos.aurokk.com/
      methods:
        password:
          enabled: true
        link:
          enabled: true
        oidc:
          enabled: true
          config:
            providers:
              - id: google
                provider: google
                client_id: ...
                client_secret: ...
                mapper_url: "base64://bG9jYWwgY2xhaW1zID0gewogIGVtYWlsX3ZlcmlmaWVkOiB0cnVlLAp9ICsgc3RkLmV4dFZhcignY2xhaW1zJyk7Cgp7CiAgaWRlbnRpdHk6IHsKICAgIHRyYWl0czogewogICAgICBbaWYgJ2VtYWlsJyBpbiBjbGFpbXMgJiYgY2xhaW1zLmVtYWlsX3ZlcmlmaWVkIHRoZW4gJ2VtYWlsJyBlbHNlIG51bGxdOiBjbGFpbXMuZW1haWwsCiAgICB9LAogIH0sCn0K"
                scope:
                  - email
                  - profile
                requested_claims:
                  id_token:
                    email:
                      essential: true
                    email_verified:
                      essential: true
      flows:
        error:
          ui_url: https://ui.kratos.aurokk.com/error
        login:
          ui_url: https://ui.kratos.aurokk.com/login
        recovery:
          enabled: true
          ui_url: https://ui.kratos.aurokk.com/recovery
        registration:
          ui_url: https://ui.kratos.aurokk.com/registration
          after:
            oidc:
              hooks:
                - hook: session
        verification:
          enabled: true
          ui_url: https://ui.kratos.aurokk.com/verification
        settings:
          ui_url: https://ui.kratos.aurokk.com/settings
    cookies:
      same_site: Strict
      domain: kratos.aurokk.com
    session:
      cookie:
        same_site: Strict
        domain: kratos.aurokk.com
  automigration:
    enabled: true
  identitySchemas:
    "user_v0.schema.json": |
      {
        "$id": "https://kratos.aurokk.com/user_v0.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "User",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "recovery": {
                    "via": "email"
                  },
                  "verification": {
                    "via": "email"
                  }
                }
              }
            }
          }
        }
      }
```

### Version

0.26.5

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Kubernetes with Helm

**Comment by aurokk** [comment]
Updated cookies settings to
```
    cookies:
      same_site: Lax
      domain: kratos.aurokk.com
    session:
      cookie:
        same_site: Lax
        domain: kratos.aurokk.com
```

And now it works. 

So, I don't understand how these cookies work, it would be nice to add some info.
Thanks!
