### ISSUE TITLE
Cross platform docker images (especially linux/arm64)

### ISSUE THREAD

**Issue by nmapx** [ory/kratos-selfservice-ui-node#331]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I've noticed self-service doesn't offer arm64 specific docker image (comparing to other Ory products) what for ARM users means they need to "fake" docker to think it's running amd64 which kinda works but is a bit hacky.

### Describe your ideal solution

```yaml
      ...
      - setup_remote_docker
      - run: docker build -t oryd/kratos-selfservice-ui-node:latest .
      - run:
          docker tag oryd/kratos-selfservice-ui-node:latest
          oryd/kratos-selfservice-ui-node:$DOCKER_SHORT_TAG
      - run:
          docker login --username "$DOCKER_USERNAME" --password
          "$DOCKER_PASSWORD"
      - run: docker push oryd/kratos-selfservice-ui-node:latest
      - run: docker push oryd/kratos-selfservice-ui-node:$DOCKER_SHORT_TAG
      ...
```
It should be plug & play if you switch to `docker buildx build ...` in CircleCI pipeline

### Workarounds or alternatives

For now it requires that ARM users use `platform: linux/amd64` on docker container startup

### Version

latest
