### ISSUE TITLE
Name and additional information not forward to kratos

### ISSUE THREAD

**Issue by jnquintin** [ory/kratos-selfservice-ui-node#375]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

I am using the docker oryd/kratos-selfservice-ui-node:v1.3.1 for the ui. I changed the file identity.schema.json to add additional required informations.
The informations are asked, on the first page of the sign up. I have a second page with the password and these informations are not forward again to kratos. which asked for them and return an error.

![Image](https://github.com/user-attachments/assets/abd38f67-64b6-47ad-ab07-c20d6b602e1a)
![Image](https://github.com/user-attachments/assets/1dfec96d-a788-44d7-a630-0a0145e28cc8)
![Image](https://github.com/user-attachments/assets/87ab826f-a6e0-4072-bb21-7b9b0d7722d7)

### Reproducing the bug

Sign up with a web browser with the identity file provided bellow.
Fill all the fields or only the required one. when the password is asked, set a password and you won't be able to sign up

### Relevant log output

```shell

```

### Relevant configuration

```yml
Docker compose:

name: ory

services:

  # Kratos (identity provider)

  kratos-migrate:
    image: oryd/kratos:v1.3.1
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos_data
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: /workspaces/experience/backend/deployments/ory/gen/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - ory

  kratos-selfservice-ui-node:
    depends_on:
      - kratos
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    ports:
      - "4455:4455"
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - HYDRA_ADMIN_URL=http://hydra:4445/
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=https://super-chainsaw-4qjg7qwpwj937p77-4433.app.github.dev
      - COOKIE_SECRET=PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
    networks:
      - ory
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.3.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --watch-courier --dev
    volumes:
      - type: volume
        source: kratos_data
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: /workspaces/experience/backend/deployments/ory/gen/kratos
        target: /etc/config/kratos
    extra_hosts:
      - "flexai-backend:host-gateway"
    networks:
      - ory

  mailslurper:
    image: marcopas/docker-mailslurper:latest
    volumes:
      - type: bind
        source: /workspaces/experience/backend/deployments/ory/gen/mailslurper/config.json
        target: /opt/mailslurper/config.json
    ports:
      - '4436:4436' # UI
      - '4437:4437' # service
      # 1025 is the SMTP port, not exposed to the host.
    networks:
      - ory

  # Hydra (OAuth 2.0 server and OIDC provider)

  hydra:
    image: oryd/hydra:v2.2.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: volume
        source: hydra_data
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: /workspaces/experience/backend/deployments/ory/gen/hydra
        target: /etc/config/hydra
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - ory

  hydra-migrate:
    image: oryd/hydra:v2.2.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: volume
        source: hydra_data
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: /workspaces/experience/backend/deployments/ory/gen/hydra
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - ory

networks:
  ory:

volumes:
  kratos_data:
  hydra_data:



hydra config:
`
serve:
  admin:
    cors:
      enabled: true
  public:
    cors:
      enabled: true
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: https://...
  consent: https://.../consent
  login: https://.../login
  logout: https://.../logout
  identity_provider:
    url: https://...
    publicUrl: https://...

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis

log:
  level: info
  format: json
  leak_sensitive_values: true


strategies:
  jwt:
    scope_claim: both

kratos:

version: v1.3.1

dsn: memory

serve:
  public:
    base_url: https://...
    cors:
      enabled: true
  admin:
    base_url: https://...

oauth2_provider:
  url: https://...

cookies:
  domain: github.dev

session:
  cookie:
    domain: github.dev

selfservice:
  default_browser_return_url: https://..../welcome
  allowed_return_urls:
    - https://...

  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
        max_breaches: 100
        min_password_length: 6
        identifier_similarity_check_enabled: false
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: https://.../error

    settings:
      ui_url: https://.../settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://.../recovery

    verification:
      enabled: true
      ui_url: https://.../verification

    logout:
      after:
        default_browser_return_url: https://.../welcome

    login:
      ui_url: https://.../login
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: require_verified_address

    registration:
      lifespan: 10m
      ui_url: https://.../registration
      after:
        password:
          hooks:
            - hook: show_verification_ui

log:
  level: info
  format: json
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  delivery_strategy: smtp
  smtp:
    connection_uri: smtp://test:test@mailslurper:1025/?disable_starttls=true&skip_ssl_verify=true
    headers: {}

feature_flags:
  use_continue_with_transitions: true


identity.schema.json:

{
  "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "maxLength": 100,
          "description": "Professional e-mail address",
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "email"
            },
            "recovery": {
              "via": "email"
            }
          }
        },
        "name": {
          "type": "object",
          "properties": {
            "first": {
              "title": "First Name",
              "type": "string"
            },
            "last": {
              "title": "Last Name",
              "type": "string"
            }
          },
          "required": [
            "first", "last"
          ]
        },
        "company": {
          "type": "string",
          "title": "Company",
          "description": "Company associated with the person",
          "minLength": 3
        },
        "phone": {
          "type": "string",
          "title": "Phone Number",
          "format": "tel",
          "description": "The phone number of the person"
        }
      },
      "required": [
        "email", "company", "name"
      ],
      "additionalProperties": false
    }
  }
}
```

### Version

1.3.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
