### ISSUE TITLE
Social sign-on fails via login page for new users

### ISSUE THREAD

**Issue by anuveyatsu** [ory/kratos-selfservice-ui-node#43]
**Describe the bug**

If I try to use login page instead of registration with a new account, it registers the account in db, however, it fails to redirect/complete the process.

**To Reproduce**

1. Clean up the db so that you can use GitHub/Google SSO that doesn't exist in the db
2. Go to `/auth/login`
3. Select Github or Google method
4. Get `ERR_EMPTY_RESPONSE`

**Expected behavior**

Redirects to default redirect url, e.g., `/dashboard`.

**Environment**

- Kratos-selfservice-ui-node: `v0.3.0-alpha.1`
- Kratos: `v0.3.0-alpha.1`
- Environment: quickstart (docker-compose)

**Additional context**

Logs:

```
kratos-selfservice-ui-node_1  | No request found in URL, initializing auth flow.
kratos-selfservice-ui-node_1  | GET /auth/login 302 148 - 42.718 ms
kratos_1                      | time="2020-05-22T12:35:39Z" level=info msg="started handling request" method=GET name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49302" request=/self-service/browser/flows/login
kratos_1                      | time="2020-05-22T12:35:44Z" level=info msg="completed handling request" method=GET name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49302" request=/self-service/browser/flows/login status=302 text_status=Found took=5.4979608s
kratos-selfservice-ui-node_1  | GET /.ory/kratos/public/self-service/browser/flows/login 302 100 - 5583.624 ms
kratos_1                      | time="2020-05-22T12:35:44Z" level=info msg="started handling request" method=GET name="admin#http://kratos:4434/" remote="172.20.0.4:46460" request="/self-service/browser/flows/requests/login?request=a1386f7e-b249-40a4-9fd9-38a87329ff8a"
kratos_1                      | time="2020-05-22T12:35:44Z" level=info msg="completed handling request" method=GET name="admin#http://kratos:4434/" remote="172.20.0.4:46460" request="/self-service/browser/flows/requests/login?request=a1386f7e-b249-40a4-9fd9-38a87329ff8a" status=200 text_status=OK took=1.9646ms
kratos-selfservice-ui-node_1  | GET /auth/login?request=a1386f7e-b249-40a4-9fd9-38a87329ff8a 200 13535 - 387.953 ms
kratos-selfservice-ui-node_1  | GET /index.css 304 - - 31.221 ms
kratos-selfservice-ui-node_1  | GET /typography.css 304 - - 35.093 ms
kratos-selfservice-ui-node_1  | GET /form.css 304 - - 25.768 ms
kratos-selfservice-ui-node_1  | GET /auth.css 304 - - 33.850 ms
kratos_1                      | time="2020-05-22T12:35:47Z" level=info msg="started handling request" method=POST name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49314" request=/self-service/browser/flows/strategies/oidc/auth/a1386f7e-b249-40a4-9fd9-38a87329ff8a
kratos_1                      | time="2020-05-22T12:35:49Z" level=info msg="completed handling request" method=POST name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49314" request=/self-service/browser/flows/strategies/oidc/auth/a1386f7e-b249-40a4-9fd9-38a87329ff8a status=302 text_status=Found took=1.7090371s
kratos-selfservice-ui-node_1  | POST /.ory/kratos/public/self-service/browser/flows/strategies/oidc/auth/a1386f7e-b249-40a4-9fd9-38a87329ff8a 302 0 - 1717.150 ms
kratos_1                      | time="2020-05-22T12:35:54Z" level=info msg="started handling request" method=GET name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49320" request="/self-service/browser/flows/strategies/oidc/callback/github?code=22a58789d5a6120b35c1&state=67bfc409-4734-424f-91bc-daf2587c8aae"
kratos_1                      | time="2020-05-22T12:35:59Z" level=debug msg="Received successful OpenID Connect callback but user is not registered. Re-initializing registration flow now." provider=github subject=17809581
kratos_1                      | time="2020-05-22T12:36:04Z" level=debug msg="OpenID Connect Jsonnet mapper completed." mapper_jsonnet_output="{\n   \"identity\": {\n      \"traits\": {\n         \"email\": \"anuar.ustayev@gmail.com\"\n      }\n   }\n}\n" mapper_jsonnet_url="file:///etc/config/kratos/oidc.github.jsonnet" oidc_claims="&{https://github.com/login/oauth/access_token 17809581 Anuar Ustayev       https://github.com/anuveyatsu https://avatars1.githubusercontent.com/u/17809581?v=4  anuar.ustayev@gmail.com true      false 1590150887}" oidc_provider=github
kratos_1                      | time="2020-05-22T12:36:06Z" level=debug msg="A new identity has registered using self-service registration. Running post execution hooks." identity_id=d39fe51c-e8e4-4f8b-919e-0f3bdd26a45c
kratos_1                      | time="2020-05-22T12:36:07Z" level=debug msg="Post registration execution hooks completed successfully." identity_id=d39fe51c-e8e4-4f8b-919e-0f3bdd26a45c
kratos_1                      | time="2020-05-22T12:36:07Z" level=info msg="completed handling request" method=GET name="public#http://127.0.0.1:4455/.ory/kratos/public/" remote="172.20.0.4:49320" request="/self-service/browser/flows/strategies/oidc/callback/github?code=22a58789d5a6120b35c1&state=67bfc409-4734-424f-91bc-daf2587c8aae" status=302 text_status=Found took=13.8210832s
kratos-selfservice-ui-node_1  | internal/streams/legacy.js:61
kratos-selfservice-ui-node_1  |       throw er; // Unhandled stream error in pipe.
kratos-selfservice-ui-node_1  |       ^
kratos-selfservice-ui-node_1  | 
kratos-selfservice-ui-node_1  | Error: socket hang up
kratos-selfservice-ui-node_1  |     at connResetException (internal/errors.js:609:14)
kratos-selfservice-ui-node_1  |     at Socket.socketOnEnd (_http_client.js:455:23)
kratos-selfservice-ui-node_1  |     at Socket.emit (events.js:333:22)
kratos-selfservice-ui-node_1  |     at endReadableNT (_stream_readable.js:1220:12)
kratos-selfservice-ui-node_1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
kratos-selfservice-ui-node_1  |   code: 'ECONNRESET'
kratos-selfservice-ui-node_1  | }
kratos-selfservice-ui-node_1  | npm ERR! code ELIFECYCLE
kratos-selfservice-ui-node_1  | npm ERR! errno 1
kratos-selfservice-ui-node_1  | npm ERR! kratos-selfservice-ui-node@0.0.1 serve: `node lib/index.js`
kratos-selfservice-ui-node_1  | npm ERR! Exit status 1
kratos-selfservice-ui-node_1  | npm ERR! 
kratos-selfservice-ui-node_1  | npm ERR! Failed at the kratos-selfservice-ui-node@0.0.1 serve script.
kratos-selfservice-ui-node_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
kratos-selfservice-ui-node_1  | 
kratos-selfservice-ui-node_1  | npm ERR! A complete log of this run can be found in:
kratos-selfservice-ui-node_1  | npm ERR!     /root/.npm/_logs/2020-05-22T12_36_07_942Z-debug.log
kratos_kratos-selfservice-ui-node_1 exited with code 1
```

**Comment by aeneasr** [comment]
Could you maybe share your Kratos config? Is this the same issue as here: https://community.ory.sh/t/ory-kratos-empty-responses-from-server-in-verification-flow/1746/14?

**Comment by anuveyatsu** [comment]
@aeneasr sure, here is the kratos config:

```yaml
selfservice:
  strategies:
    oidc:
      enabled: true
      config:
        providers:
        - id: github
          provider: github
          client_id: ...
          client_secret: ...
          mapper_url: file:///etc/config/kratos/oidc.github.jsonnet
          scope:
          - user:email
          - read:user
        - id: google
          provider: google
          client_id: ...
          client_secret: ...
          mapper_url: file:///etc/config/kratos/oidc.google.jsonnet
          scope:
          - email

  settings:
    privileged_session_max_age: 1m

  logout:
    redirect_to: http://127.0.0.1:4455/auth/login

  login:
    request_lifespan: 100m

  registration:
    request_lifespan: 100m
    after:
      password:
        hooks:
          -
            hook: session
      oidc:
        hooks:
          -
            hook: session

log:
  level: debug

secrets:
  session:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

urls:
  login_ui: http://127.0.0.1:4455/auth/login
  registration_ui: http://127.0.0.1:4455/auth/registration
  error_ui: http://127.0.0.1:4455/error
  settings_ui: http://127.0.0.1:4455/settings
  verify_ui: http://127.0.0.1:4455/verify

  # These are undefined because not available in this demo
  mfa_ui: http://127.0.0.1:4455/

  self:
    public: http://127.0.0.1:4455/.ory/kratos/public/
    admin: http://kratos:4434/
  default_return_to: http://127.0.0.1:4455/dashboard
  whitelisted_return_to_urls:
    - http://127.0.0.1:4455

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  traits:
    default_schema_url: file:///etc/config/kratos/identity.traits.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```
