### ISSUE TITLE
Redirect loop on domain-based configurations

### ISSUE THREAD

**Issue by programmador** [ory/kratos-selfservice-ui-node#60]
**Describe the bug**

We don't use port-based configs in our development environment. Instead we've generated a root cert and then lots of certificates for all of services including Kratos, Hydra and many more. And there's an issue with kratos-selfservice-ui-node in such kind of config: it uses broken 'Host:' header while trying to fetch data from public api which causes reverse proxy misbehaviour in configurations where such kind of proxy knows smth about both domains: one for Kratos and other for kratos-selfservice-ui-node.

**To Reproduce**

One example is a config for Traefik 1.7 for Kratos:
```
labels:
            traefik.enable: true
            traefik.api.frontend.rule: "Host: api.kratos.local"
            traefik.api.port: '4433'
            traefik.api.protocol: 'http'
            traefik.api.frontend.headers.SSLRedirect: false
            traefik.admin.frontend.rule: "Host: admin.kratos.local"
            traefik.admin.port: '4434'
            traefik.admin.protocol: 'http'
            traefik.admin.frontend.headers.SSLRedirect: false
```
and for ui-node:
```
        labels:
            traefik.enable: true
            traefik.frontend.rule: "Host: ui.kratos.local"
            traefik.port: '80'
            traefik.protocol: 'http'
            traefik.frontend.headers.SSLRedirect: true
```
Other example is nginx config for both:
```
server {
    listen          80;
    server_name     ui.kratos.local;
    location / {
        proxy_pass  http://kratos-sample-app:80/;
    }
}

server {
    listen          80;
    server_name     api.kratos.local;
    location / {
        proxy_pass  http://kratos:4433/;
    }
}
```

**Actual behavior**

ui-node sets it's own domain `ui.kratos.local` while piping request to api.kratos.local in `Host:` header.
This is HTTP 1.1 violation. Host header is intended to be used by webserver in configurations where a single destination can lead to different virtualhosts.

So if webserver knows smth. about both used domains (ui.kratos.local & api.kratos.local) - it routes the request to wrong location. Even if the destination is `api.kratos.local` the request will be routed to `ui.kratos.local` as in `Host:` header.

The behaviour differs between webservers. Traefik returns 302-redirect which in turn redirects to ui.kratos.node and the redirect loop starts over. As opposed to Traefik, Nginx does not try to generate redirect and instead itself routes the request to ui.kratos.local where it gets the same type of response: a redirect.

So though Traefik and Nginx have different logic of handling such ill requests, both ways of handling cause a redirect loop for a browser

**Expected behavior**

`/dashboard` or `/` should be opened after login instead of looping infinitely through redirects just after logging in.
