### ISSUE TITLE
Support for configuring and enabling HTTPS

### ISSUE THREAD

**Issue by programmador** [ory/kratos-selfservice-ui-node#62]
Wait a bit, I'll perform some forking/merging/etc stuff and create a PR.
I already have a working version.
Docker-compose example:
```
        environment:
            PORT: 443
            TLS_KEY_PATH: '/certificates/certificate.key'
            TLS_CERT_PATH: '/certificates/certificate.crt'
            ...more_vars
        volumes:
            - 'path/to/abovementioned/cert/files:/certificates:ro'
            ...more_volumes
```
